# Etapa build
FROM node:20-alpine AS builder

WORKDIR /app

# 👇 Declaras el ARG
ARG VITE_API_URL

# 👇 Lo conviertes en variable de entorno para el build
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Etapa producción
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]